// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIFOkHGErTqa5nwOmDpoLkOukVow_Vwfc',
    appId: '1:271012539406:web:910d7a81fad0001546205f',
    messagingSenderId: '271012539406',
    projectId: 'fir-ed6e0',
    authDomain: 'fir-ed6e0.firebaseapp.com',
    storageBucket: 'fir-ed6e0.appspot.com',
    measurementId: 'G-MBDEFEKXLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMVO565M-zY_acgiJmuYxHmZJSqfZCV4o',
    appId: '1:271012539406:android:da3f2803c31548bd46205f',
    messagingSenderId: '271012539406',
    projectId: 'fir-ed6e0',
    storageBucket: 'fir-ed6e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYcNs9vdFd4L3V0IZywQKssaTp9a5AUAo',
    appId: '1:271012539406:ios:453f347fcec900ef46205f',
    messagingSenderId: '271012539406',
    projectId: 'fir-ed6e0',
    storageBucket: 'fir-ed6e0.appspot.com',
    iosBundleId: 'com.example.firebasebot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYcNs9vdFd4L3V0IZywQKssaTp9a5AUAo',
    appId: '1:271012539406:ios:453f347fcec900ef46205f',
    messagingSenderId: '271012539406',
    projectId: 'fir-ed6e0',
    storageBucket: 'fir-ed6e0.appspot.com',
    iosBundleId: 'com.example.firebasebot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIFOkHGErTqa5nwOmDpoLkOukVow_Vwfc',
    appId: '1:271012539406:web:5a8fe5ce34d5d2f346205f',
    messagingSenderId: '271012539406',
    projectId: 'fir-ed6e0',
    authDomain: 'fir-ed6e0.firebaseapp.com',
    storageBucket: 'fir-ed6e0.appspot.com',
    measurementId: 'G-3RMHPDRRVG',
  );

}